name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  metadata-publish:
    name: Publish Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Metadata
        run: ./gradlew publish --info -Pbuild_type=METADATA -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  non-native-publish:
    name: Publish JVM, Android, JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish JVM, Android, JS
        run: ./gradlew publish --info -Pbuild_type=NON_NATIVE -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  linux-publish:
    name: Publish Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Linux
        run: ./gradlew publish --info -Pbuild_type=LINUX -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  ios-publish:
    name: Publish iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish iOS
        run: ./gradlew publish -Pbuild_type=IOS -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  macos-publish:
    name: Publish macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish macOS
        run: ./gradlew publish --info -Pbuild_type=MAC_OS -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
#  non-native-check-publication:
#    name: Check JVM, Android, JS publication
#    runs-on: ubuntu-latest
#    needs: [metadata-publish, non-native-publish]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Install Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Update dependencies
#        run: sudo apt-get update
#      - name: Install dependencies
#        run: sudo apt-get install nodejs chromium-browser
#      - name: Check JVM, Android, JS publication
#        run: ./gradlew :tools:check-publication:build --info -Pcheck_publication=true -Pbuild_type=NON_NATIVE -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
#  linux-check-publication:
#    name: Check Linux publication
#    runs-on: ubuntu-latest
#    needs: [metadata-publish, linux-publish]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Install Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Check Linux publication
#        run: ./gradlew :tools:check-publication:build --info -Pcheck_publication=true -Pbuild_type=LINUX -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
#  ios-check-publication:
#    name: Check iOS publication
#    runs-on: macos-latest
#    needs: [metadata-publish, ios-publish]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Install Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Check iOS publication
#        run: ./gradlew :tools:check-publication:build --info -Pcheck_publication=true -Pbuild_type=IOS -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
#  macos-check-publication:
#    name: Check macOS publication
#    runs-on: macos-latest
#    needs: [metadata-publish, macos-publish]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Install Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Check macOS publication
#        run: ./gradlew :tools:check-publication:build --info -Pcheck_publication=true -Pbuild_type=MAC_OS -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
